### ISSUE TITLE
Can't set scxml/@initial to a nested state

### ISSUE THREAD

**Issue by mattoshry** [jbeard4/SCION#327] opened 2015-01-23 06:46 UTC
&lt;scxml xmlns="http://www.w3.org/2005/07/scxml"
  version="1.0" initial="s2">

&lt;state id="uber">
  &lt;state id="s1">
    &lt;onentry>
      &lt;log expr="'onentry s1 _sessionid=' + _sessionid" label="TEST"/>
    &lt;/onentry>
    &lt;transition event="ev1" target="s2"/>
  &lt;/state>

  &lt;state id="s2">
    &lt;onentry>
      &lt;log expr="'onentry s2 _sessionid=' + _sessionid" label="TEST"/>
    &lt;/onentry>
  &lt;/state>
&lt;/state>
&lt;/scxml>

Scion throws here:
/Users/matto/git/scxml/node_modules/scxml/node_modules/scion-core/lib/scion.js:190
                if(!state.initialRef) throw new Error('Unable to locate initia                                            ^
Error: Unable to locate initial state for composite state: undefined

**Comment by jbeard4** [comment] 2015-01-23 14:37
The issue is in the model initialization code in SCION-CORE here https://github.com/jbeard4/SCION-CORE/blob/master/lib/scion.js#L187
Which assumes that the initial state will be a substate. This is an erroneous assumption. 

The solution will be to hook the initial state logic into connectTransitionGraph:
https://github.com/jbeard4/SCION-CORE/blob/master/lib/scion.js#L216

ETA Monday

**Comment by jbeard4** [comment] 2015-01-27 14:35
Fixed in PR #335

**Closed by jbeard4** 2015-01-27 14:35 UTC
